# This is a config for E2B sandbox template.
# You can use template ID (fbafr3asc4bofawmew8b) or template name (v0-build-clone) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("v0-build-clone") # Sync sandbox
# sandbox = await AsyncSandbox.create("v0-build-clone") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('v0-build-clone')

team_id = "d79ec0f9-825f-4a31-ae00-8bca66617be1"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "v0-build-clone"
template_id = "fbafr3asc4bofawmew8b"
